title: Stephen
description: Cookies. Coding. Cumbersome Writing.
meta_description: "The blog of Stephen McGruer"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://stephenmcgruer.com'
google_analytics: 'UA-XXXXXXXX-X'
#gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://stephenmcgruer.com'
author:         'Stephen McGruer'

gems: ['kramdown', 'jekyll-paginate']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
