url: http://stephenmcgruer.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
pygments: true

exclude: [config.ru, Gemfile, Gemfile.lock, LICENSE.txt, Procfile, Rakefile, README.md]

name:     Stephen McGruer
nickname: stephenmcgruer
